# Generated by Django 4.0.3 on 2022-04-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-main_tag', 'tag__name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
